networks:
  hg-e2e:
    external: true

services:
  hive-metastore:
    image: apache/hive:4.1.0
    container_name: hive-metastore
    hostname: hive-metastore
    user: root
    environment:
      - SERVICE_NAME=metastore
    ports:
      - "9083:9083"       # Thrift Metastore API
    volumes:
      - ./conf/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./conf/hadoop/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./conf/hadoop/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./conf/hadoop/workers:/opt/hadoop/etc/hadoop/workers
      - ./conf/hive/hive-site.xml:/opt/hive/conf/hive-site.xml
      - ./scripts/hive/hive-entrypoint.sh:/hive-entrypoint.sh
    command: ["/bin/bash", "/hive-entrypoint.sh"]
    # Healthcheck waits until the thrift port is open
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/9083'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - hg-e2e

  hive-hiveserver2:
    image: apache/hive:4.1.0
    container_name: hive-hiveserver2
    hostname: hive-hiveserver2
    user: root
    environment:
      - SERVICE_NAME=hiveserver2
      - SERVICE_OPTS=-Dhive.metastore.uris=thrift://hive-metastore:9083
      - IS_RESUME=true
    depends_on:
      hive-metastore:
        condition: service_healthy
    ports:
      - "10000:10000"     # JDBC/Beeline
      - "10002:10002"     # WebUI
    volumes:
      - ./conf/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./conf/hadoop/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./conf/hadoop/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./conf/hadoop/workers:/opt/hadoop/etc/hadoop/workers
      - ./conf/hive/hive-site.xml:/opt/hive/conf/hive-site.xml
      - ./scripts/hive/hive-entrypoint.sh:/hive-entrypoint.sh
    command: ["/bin/bash", "/hive-entrypoint.sh"]
    networks:
      - hg-e2e
